displayName=Party Link
author=havardpede
description=Remotely control RuneLite parties from an external web server
tags=party,potionstorage,potion,storage,remote,automation,websocket,group
plugins=com.github.havardpede.partylink.LinkPlugin